### ISSUE TITLE
Item tag should be editable during the session

### ISSUE THREAD

**Issue by mariesayadchi** [Esensorics/esensoricsDevelopment#7]
after some initial tag is set, one should be able to change it.

**Comment by MariaMedinatu** [comment]
I found some tagging options that I refer to in the folder "tagit" in my personal folder. I consider them useful and appropriate to name the axes too. Next step would be to be able to assign them to the items in the grid. I found them at http://webscripts.softpedia.com/dyn-postdownload.php/1968ed78ff319866949fc71044552df6/551bff99/10765/0/1
